{
  "formatVersion": "1.1",
  "component": {
    "group": "TransformTest1",
    "module": "plugin",
    "version": "unspecified",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "plugin-unspecified.jar",
          "url": "plugin-unspecified.jar",
          "size": 8381,
          "sha512": "26cc3b748097983c0afa4f602648720c941f65491b225d1a0b015d8eabd81ef0013ab34c2b851f415f11934f1129a47abf77b049f20dbda21e4a420208c76246",
          "sha256": "f92a094ef5e054e78a462d0f0504a00e10e444c9c47ac11ed46597ac477ca0cb",
          "sha1": "13492ea75da37c59c8edeb873f9531371e054ed7",
          "md5": "a79a899c61476693b6f24112dbee8208"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.testng",
          "module": "testng",
          "version": {
            "requires": "7.4.0"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.1.3"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-gradle-plugin",
          "version": {
            "requires": "2.4.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-io",
          "version": {
            "requires": "1.3.2"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-unspecified.jar",
          "url": "plugin-unspecified.jar",
          "size": 8381,
          "sha512": "26cc3b748097983c0afa4f602648720c941f65491b225d1a0b015d8eabd81ef0013ab34c2b851f415f11934f1129a47abf77b049f20dbda21e4a420208c76246",
          "sha256": "f92a094ef5e054e78a462d0f0504a00e10e444c9c47ac11ed46597ac477ca0cb",
          "sha1": "13492ea75da37c59c8edeb873f9531371e054ed7",
          "md5": "a79a899c61476693b6f24112dbee8208"
        }
      ]
    }
  ]
}
