/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.example.plugin;

import org.gradle.api.Project;

import com.android.build.gradle.AppExtension;

import org.gradle.api.Plugin;

/**
 * A simple 'hello world' plugin.
 */
public class Plugin_project_namePlugin implements Plugin<Project> {
    public void apply(Project project) {
        AppExtension appExtension=project.getExtensions().findByType(AppExtension.class);
        assert appExtension != null;
        appExtension.registerTransform(new MyTransform(project));
    }
}
